# Generated by Django 4.1.7 on 2023-08-10 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(default=1)),
                ('seconds_per_person', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QueuedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('playing_at', models.DateTimeField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True)),
                ('finished_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished', to=settings.AUTH_USER_MODEL)),
                ('playing_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playing', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_people', to='gamequeue.gamequeue')),
                ('queued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
